#!/bin/bash
gcc -Wall I3_1.c -o I3_1
if [ $#==3 ]; then
    rec -t raw -b 16 -c 1 -e s -r 44100 - | ./I3_1 $1 $2 | play -t raw -b 16 -c 1 -e s -r 44100 -
else
    rec -t raw -b 16 -c 1 -e s -r 44100 - | ./I3_1 $1 | play -t raw -b 16 -e s -r 44100 -
fi