#!/bin/bash
if [ $#==3 ]; then
    rec -t raw -b 16 -c 1 -e s -r 44100 - | nc $1 $2 -v | play -t raw -b 16 -c 1 -e s -r 44100 -
else
    rec -t raw -b 16 -c 1 -e s -r 44100 - | nc -l $1 -v | play -t raw -b 16 -e s -r 44100 -
fi